apiVersion: v1
kind: Pod
metadata:
  name: sp1-pod
  namespace: sp1
  annotations:
    memo: simple-www-pod
  labels:
    app: www
    release: beta
spec:
  containers:
    - name: nginx-container
      image: nginx
    - name: memcached-container
      image: memcached
    - name: redis-container
      image: redis
