apiVersion: v1
kind: Pod
metadata:
  name: sp3-pod
  namespace: sp3
  annotations:
    memo: dual-www-pod
  labels:
    app: www
spec:
  containers:
    - name: nginx-container
      image: nginx
    - name: httpd-container
      image: httpd
